import { Locator, Page } from '@playwright/test';
import { PageManager } from "@utils/PageManager";

/**
 * This class provides utility functions for All Loads Search Page.
 * @author Tejaswini
 * @param pages Page object manager
 * @param testData Test data for the load
 */
export default class AllLoadsSearchPage {

    private readonly checkAll_LOC: Locator;
    private readonly bulkChange_LOC: Locator;
    private readonly searchbutton_LOC: Locator;
    private readonly searchLoads_LOC: Locator;
  // Auto-generated locators by AI Agent
  private readonly newLoadDropdown_LOC: Locator;

    
    constructor(private page: Page) {
        this.checkAll_LOC = this.page.locator("//input[@id='master_cb']");
        this.bulkChange_LOC = this.page.locator("//button[@id='bulk-change-button']");
        this.searchbutton_LOC = this.page.locator("//input[@class='submit-report-search']");
        this.searchLoads_LOC = this.page.locator("//input[@id='search_loadsh_ids']");
    // Auto-generated locator assignments by AI Agent
    this.newLoadDropdown_LOC = page.locator("//*[contains(text(),'New Load Dropdown')] | //button[contains(text(),'New Load Dropdown')] | //input[contains(@value,'New Load Dropdown')]");
    }   

    /**
    * Selects all available loads in the All Load Search results page.
    */
    async selectAllLoads(): Promise<void> {
        await this.checkAll_LOC.check();
    }

    /**
    * Clicks on the Bulk Change button on All Load Search results page.
    */
    async clickBulkChangeButton(): Promise<void> {
        await this.bulkChange_LOC.click();
    }

    /**
     * Searches for multiple loads using their load numbers
     * @param loadNumbers 
     */
    async searchMultipleLoads(loadNumbers: string[], pages: PageManager): Promise<void> {
        const cleaned = loadNumbers.map(n => (n || '').toString().trim()).filter(Boolean);
        const loadsToSearch = cleaned.join(',');
        const maxAttempts = 3;
        for (let attempt = 1; attempt <= maxAttempts; attempt++) {
            console.log(`searchMultipleLoads attempt ${attempt}/${maxAttempts}`);
            await this.searchLoads_LOC.fill(loadsToSearch);
            await this.searchbutton_LOC.scrollIntoViewIfNeeded();
            await this.searchbutton_LOC.waitFor({ state: 'visible' });
            await Promise.all([
                this.searchbutton_LOC.click(),
                this.page.waitForLoadState('networkidle', { timeout: WAIT.SPEC_TIMEOUT })
            ]);

            // Inspect page content for known PHP implode error which sometimes appears when server receives bad input
            const bodyText = await this.page.content();
            if (bodyText.includes("TypeError: implode(): Argument #2" ) || bodyText.includes('implode(')) {
                console.warn('Detected server implode error after search. Retrying...');
                // Navigate back to reset the page state before retrying the search
                try {
                    await this.page.goBack({ waitUntil: 'domcontentloaded' });
                } catch (e) {
                    console.warn('goBack failed or no history available:', e ?? e);
                }
                await this.page.waitForTimeout(WAIT.DEFAULT * attempt);
                await pages.basePage.clickHomeButton();
                await pages.basePage.waitForMultipleLoadStates(['networkidle']);
                await pages.basePage.hoverOverHeaderByText(HEADERS.LOAD);
                await pages.basePage.clickSubHeaderByText(LOAD_SUB_MENU.SEARCH);

                continue;
            }
            return;
        }
        throw new Error('searchMultipleLoads: server returned PHP implode error after multiple attempts');
    }


  /**
   * clickNewLoadDropdown - Auto-generated by AI Agent
   * @author AI Agent Generator
   * @created 2026-02-12
   */
  async clickNewLoadDropdown(): Promise<void> {
    await this.newLoadDropdown_LOC.waitFor({ state: 'visible', timeout: 10000 });
    await this.newLoadDropdown_LOC.click();
    console.log('Clicked on New Load Dropdown');
  }

  /**
   * selectNonTabularTL - Auto-generated by AI Agent
   * @author AI Agent Generator
   * @created 2026-02-12
   */
  async selectNonTabularTL(value: string): Promise<void> {
    const dropdown = this.page.locator('[id*="nonTabularTL"], [name*="nonTabularTL"]').first();
    await dropdown.click();
    const option = this.page.locator(`//*[contains(text(),'${value}')]`);
    await option.click();
    console.log(`Selected ${value} for Non Tabular T L`);
  }
}