import { Locator, Page } from '@playwright/test';

class LoadsPage {

    private readonly edi204LoadTenderLink_LOC: Locator;
    /**
     * Constructor to initialize page locators for Loads page
     * @author Rohit Singh
     * @created 2025-07-18
     */
  // Auto-generated locators by AI Agent
  private readonly newLoadDropdown_LOC: Locator;
  // Auto-generated locators by AI Agent
  private readonly nonTabularTLDropdown_LOC: Locator;


    constructor(private page: Page) {
        this.edi204LoadTenderLink_LOC = page.locator("//a[text()='EDI 204 Load Tenders']");
    // Auto-generated locator assignments by AI Agent
    this.newLoadDropdown_LOC = page.locator("//*[contains(text(),'New Load Dropdown')] | //button[contains(text(),'New Load Dropdown')] | //input[contains(@value,'New Load Dropdown')]");
    // Auto-generated locator assignments by AI Agent
    this.nonTabularTLDropdown_LOC = page.locator("[id*=\"nonTabularTL\"], [name*=\"nonTabularTL\"]");
    }
    /**
     * Clicks on the EDI 204 Load Tender link
     * @author Rohit Singh
     * @created 2025-07-18
     */
    async clickOnEDI204LoadTender() {
        await this.edi204LoadTenderLink_LOC.click();
        await this.page.waitForLoadState('networkidle'); // Wait for the page to load
    }

  /**
   * clickNewLoadDropdown - Auto-generated by AI Agent
   * @author AI Agent
   * @created 29-Apr-2026
   */
  async clickNewLoadDropdown(): Promise<void> {
    await this.newLoadDropdown_LOC.waitFor({ state: 'visible', timeout: 10000 });
    await this.newLoadDropdown_LOC.click();
    console.log('Clicked on New Load Dropdown');
  }

  /**
   * selectNonTabularTL - Auto-generated by AI Agent
   * @author AI Agent
   * @created 29-Apr-2026
   */
  async selectNonTabularTL(value: string): Promise<void> {
    await this.nonTabularTLDropdown_LOC.first().click();
    const option = this.page.locator(`//*[contains(text(),'${value}')]`);
    await option.click();
    console.log(`Selected ${value} for Non Tabular T L`);
  }
}
export default LoadsPage;