import { Locator, Page } from "@playwright/test";
import commonReusables from "@utils/commonReusables";

export default class AgentAccountsPage {
    private readonly agentNameLink_LOC: (userName: string) =>Locator;
  // Auto-generated locators by AI Agent
  private readonly userIdAndClickNextInput_LOC: Locator;

    constructor(private page: Page) {
        this.agentNameLink_LOC = (userName: string) => this.page.locator(`//a[contains(text(),'${userName}')]`);
    // Auto-generated locator assignments by AI Agent
    this.userIdAndClickNextInput_LOC = page.locator("#userIdAndClickNext, [name*='userIdAndClickNext'], [placeholder*='User Id And Click Next']");
    }

    /**
     * @author Rohit Singh
     * @created 09-Jan-2026
     * @param userName - Agent User Name
     * @throws Error if username is not visible on the page
     */
    async clickOnUserNameIfVisible(userName: string): Promise<void> {
        console.log(`Clicking on user name: ${userName}`);
        await commonReusables.waitForPageStable(this.page);
        if(userName.toUpperCase() === "SVC.TESTAUTOMATION")
        {
            userName = "SVC_TESTAUTOMATION";
        }
        const isVisible = await this.agentNameLink_LOC(userName).isVisible();
        if (!isVisible) {
            throw new Error(`Username not found in Agent Accounts Page: ${userName}`);
        }
        await this.agentNameLink_LOC(userName).click();
    }


  /**
   * enterUserIdAndClickNext - Auto-generated by AI Agent
   * @author AI Agent
   * @created 01-Jun-2026
   */
  async enterUserIdAndClickNext(value: string): Promise<void> {
    await this.userIdAndClickNextInput_LOC.waitFor({ state: 'visible', timeout: 10000 });
    await this.userIdAndClickNextInput_LOC.fill(value);
    console.log(`Entered ${value} in User Id And Click Next`);
  }
}